# Generated by Django 5.1.7 on 2025-03-28 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
